/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfiches;
import javax.swing.JOptionPane;
import ptraitement.*;

/**
 *
 * @author maxen
 */
public class FAcceuilPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAcceuilPrincipal.class.getName());
    private FConnection fichFConnection;
    private FInscription fichFInscription;
    private Salle salle;
    private FListeActivites fichListeActivites;
    private FChoixPasses_Futures fichChoixPasses_Futures;
    private FMonProfil fichMonProfil;
    private Client client;
   
    
    /**
     * Creates new form FAcceuilPrincipal
     */
    public FAcceuilPrincipal() {
        initComponents();
        salle = new Salle("LE SPORT AU MAX", "sauvegarde_clients.txt");
        salle.Charger();
        salle.trierCours();

        
        fichFConnection = new FConnection(this, true, salle);
        fichFInscription = new FInscription(this, true, salle);
        fichListeActivites = new FListeActivites (this,true,salle,null);
        
        this.setPreferredSize(new java.awt.Dimension(600, 500)); // Taille adaptée à votre contenu
        this.pack(); // Applique la taille
        this.setLocationRelativeTo(null); // CENTRE sur l'écran
        

    }
    
    public Salle getSalle(){
        return this.salle;
    }
    
    
    public FMonProfil getfichMonProfil(){return this.fichMonProfil;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BOui = new javax.swing.JToggleButton();
        BNon = new javax.swing.JToggleButton();
        bQuitter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bAdmin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BIENVENUE A SPORT AU MAX");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Êtes-vous déjà client : ");

        BOui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BOui.setText("Oui");
        BOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOuiActionPerformed(evt);
            }
        });

        BNon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BNon.setText("Non");
        BNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNonActionPerformed(evt);
            }
        });

        bQuitter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bQuitter.setText("Quitter");
        bQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitterActionPerformed(evt);
            }
        });

        bAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bAdmin.setText("acces Admin");
        bAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdminActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimage/Thibthib.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimage/Maxou.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addComponent(BOui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BNon))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel5)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(bAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bQuitter)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bQuitter)
                            .addComponent(bAdmin))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(BOui)
                            .addComponent(BNon))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOuiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichFConnection.setVisible(true);
        
/*
        ptraitement.Salle maSalle = new ptraitement.Salle("LE SPORT AU MAX", "sauvegarde_clients.txt");
    maSalle.Charger();

    // 2. On crée le JDialog en lui passant 'this' (le parent) et la salle
    FConnection dialConnexion = new FConnection(this, true, maSalle);
    
    // 3. On centre et on affiche
    dialConnexion.setLocationRelativeTo(null);
    dialConnexion.setVisible(true);
        */
    }//GEN-LAST:event_BOuiActionPerformed

    private void bQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bQuitterActionPerformed

    private void BNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichFInscription.setVisible(true);
    }//GEN-LAST:event_BNonActionPerformed

    private void bAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichFConnection.setVisible(true);
    }//GEN-LAST:event_bAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FAcceuilPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BNon;
    private javax.swing.JToggleButton BOui;
    private javax.swing.JButton bAdmin;
    private javax.swing.JButton bQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
