/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfiches;
import javax.swing.JOptionPane;
import ptraitement.*;

/**
 *
 * @author maxen
 */
public class FAcceuilPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAcceuilPrincipal.class.getName());
    private FConnection fichFConnection;
    private FInscription fichFInscription;
    private Salle salle;
    private FListeActivites fichListeActivites;
    private FChoixPasses_Futures fichChoixPasses_Futures;
    private FMonProfil fichMonProfil;
    private Client client;
   
    
    /**
     * Creates new form FAcceuilPrincipal
     */
    public FAcceuilPrincipal() {
        initComponents();
        salle = new Salle("LE SPORT AU MAX", "sauvegarde_clients.txt");
        salle.Charger();

        fichFConnection = new FConnection(this, false, salle);
        fichFInscription = new FInscription(this, false, salle);
        

        fichFConnection = new FConnection(this,false,salle);
        fichFInscription = new FInscription(this, false,salle);
        fichListeActivites = new FListeActivites (this,false,salle);
       

    }
    
    public Salle getSalle(){
        return this.salle;
    }
    
    
    public FMonProfil getfichMonProfil(){return this.fichMonProfil;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BOui = new javax.swing.JToggleButton();
        BNon = new javax.swing.JToggleButton();
        bQuitter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENUE A SPORT AU MAX");

        jLabel2.setText("Êtes-vous déjà client : ");

        BOui.setText("Oui");
        BOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOuiActionPerformed(evt);
            }
        });

        BNon.setText("Non");
        BNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNonActionPerformed(evt);
            }
        });

        bQuitter.setText("Quitter");
        bQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitterActionPerformed(evt);
            }
        });

        bAdmin.setText("acces Admin");
        bAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(BOui)
                                .addGap(35, 35, 35)
                                .addComponent(BNon))
                            .addComponent(bAdmin))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bQuitter)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BOui)
                    .addComponent(BNon))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addComponent(bAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(bQuitter)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOuiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichFConnection.setVisible(true);
        
/*
        ptraitement.Salle maSalle = new ptraitement.Salle("LE SPORT AU MAX", "sauvegarde_clients.txt");
    maSalle.Charger();

    // 2. On crée le JDialog en lui passant 'this' (le parent) et la salle
    FConnection dialConnexion = new FConnection(this, true, maSalle);
    
    // 3. On centre et on affiche
    dialConnexion.setLocationRelativeTo(null);
    dialConnexion.setVisible(true);
        */
    }//GEN-LAST:event_BOuiActionPerformed

    private void bQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bQuitterActionPerformed

    private void BNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichFInscription.setVisible(true);
    }//GEN-LAST:event_BNonActionPerformed

    private void bAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichFConnection.setVisible(true);
    }//GEN-LAST:event_bAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FAcceuilPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BNon;
    private javax.swing.JToggleButton BOui;
    private javax.swing.JButton bAdmin;
    private javax.swing.JButton bQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
