/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfiches;
import ptraitement.*;

/**
 *
 * @author maxen
 */
public class FAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAdmin.class.getName());
    private FConsulter_Liste_Clients fichFConsulter_Liste_Clients;
    private FGestion_Cours fichFGestion_Cours;
    private Salle salle;
    /**
     * Creates new form FAdmin
     */
    public FAdmin(Salle salle) {
        initComponents();
        this.salle = salle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BConsulter_La_Liste_Des_Clients = new javax.swing.JButton();
        BGestion_Des_Cours = new javax.swing.JButton();
        BStatistique = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BConsulter_La_Liste_Des_Clients.setText("Consulter la liste des Clients");
        BConsulter_La_Liste_Des_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsulter_La_Liste_Des_ClientsActionPerformed(evt);
            }
        });

        BGestion_Des_Cours.setText("Gestion des cours ");
        BGestion_Des_Cours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGestion_Des_CoursActionPerformed(evt);
            }
        });

        BStatistique.setText("Statistique");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BStatistique)
                    .addComponent(BGestion_Des_Cours)
                    .addComponent(BConsulter_La_Liste_Des_Clients))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(BConsulter_La_Liste_Des_Clients)
                .addGap(18, 18, 18)
                .addComponent(BGestion_Des_Cours)
                .addGap(40, 40, 40)
                .addComponent(BStatistique)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BConsulter_La_Liste_Des_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsulter_La_Liste_Des_ClientsActionPerformed
        // TODO add your handling code here:
        fichFConsulter_Liste_Clients = new FConsulter_Liste_Clients(this, true, this.salle);
        this.setVisible(false);
        fichFConsulter_Liste_Clients.setVisible(true);
    }//GEN-LAST:event_BConsulter_La_Liste_Des_ClientsActionPerformed

    private void BGestion_Des_CoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGestion_Des_CoursActionPerformed
        // TODO add your handling code here:
        fichFGestion_Cours = new FGestion_Cours(this, true, this.salle);
        this.setVisible(false);
        fichFGestion_Cours.setVisible(true);
    }//GEN-LAST:event_BGestion_Des_CoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new FAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConsulter_La_Liste_Des_Clients;
    private javax.swing.JButton BGestion_Des_Cours;
    private javax.swing.JButton BStatistique;
    // End of variables declaration//GEN-END:variables
}
