/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;
import ptraitement.*;
/**
 *
 * @author maxen
 */
public class FAdmin extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAdmin.class.getName());
    private FConsulter_Liste_Clients fichFConsulter_Liste_Clients;
    private FGestion_Cours fichFGestion_Cours;
    private FStatistique_Cours fichFStatistique_Cours;
    private Salle salle;
    private javax.swing.JDialog parent;
    /**
     * Creates new form FAdmin
     */
    public FAdmin(javax.swing.JDialog parent, boolean modal,  Salle salle) {
        super(parent, modal);
        initComponents();
        this.salle = salle;
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BConsulter_La_Liste_Des_Clients = new javax.swing.JButton();
        BGestion_Des_Cours = new javax.swing.JButton();
        BStatistique = new javax.swing.JButton();
        BRetour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BConsulter_La_Liste_Des_Clients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimage/logo client liste.png"))); // NOI18N
        BConsulter_La_Liste_Des_Clients.setBorderPainted(false);
        BConsulter_La_Liste_Des_Clients.setContentAreaFilled(false);
        BConsulter_La_Liste_Des_Clients.setMaximumSize(new java.awt.Dimension(100, 100));
        BConsulter_La_Liste_Des_Clients.setMinimumSize(new java.awt.Dimension(100, 100));
        BConsulter_La_Liste_Des_Clients.setPreferredSize(new java.awt.Dimension(100, 100));
        BConsulter_La_Liste_Des_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsulter_La_Liste_Des_ClientsActionPerformed(evt);
            }
        });
        getContentPane().add(BConsulter_La_Liste_Des_Clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 250, 270));

        BGestion_Des_Cours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimage/logo gestion cours.png"))); // NOI18N
        BGestion_Des_Cours.setToolTipText("");
        BGestion_Des_Cours.setBorderPainted(false);
        BGestion_Des_Cours.setContentAreaFilled(false);
        BGestion_Des_Cours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGestion_Des_CoursActionPerformed(evt);
            }
        });
        getContentPane().add(BGestion_Des_Cours, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 270, 270));

        BStatistique.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimage/logo statiques.png"))); // NOI18N
        BStatistique.setBorderPainted(false);
        BStatistique.setContentAreaFilled(false);
        BStatistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BStatistiqueActionPerformed(evt);
            }
        });
        getContentPane().add(BStatistique, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 260, 270));

        BRetour.setText("Retour");
        BRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetourActionPerformed(evt);
            }
        });
        getContentPane().add(BRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 333, 80, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -90, 1690, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BConsulter_La_Liste_Des_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsulter_La_Liste_Des_ClientsActionPerformed
        // TODO add your handling code here:
        fichFConsulter_Liste_Clients = new FConsulter_Liste_Clients(this, true, this.salle);
        this.setVisible(false);
        fichFConsulter_Liste_Clients.setVisible(true);
    }//GEN-LAST:event_BConsulter_La_Liste_Des_ClientsActionPerformed

    private void BGestion_Des_CoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGestion_Des_CoursActionPerformed
        // TODO add your handling code here:
        fichFGestion_Cours = new FGestion_Cours(this, true, this.salle);
        this.setVisible(false);
        fichFGestion_Cours.setVisible(true);
    }//GEN-LAST:event_BGestion_Des_CoursActionPerformed

    private void BStatistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BStatistiqueActionPerformed
        // TODO add your handling code here:
        fichFStatistique_Cours = new FStatistique_Cours(this, true, this.salle);
        this.setVisible(false);
        fichFStatistique_Cours.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_BStatistiqueActionPerformed

    private void BRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetourActionPerformed
        // TODO add your handling code here:
        
        if(parent != null){
            parent.setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_BRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FAdmin dialog = new FAdmin(new javax.swing.JDialog(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConsulter_La_Liste_Des_Clients;
    private javax.swing.JButton BGestion_Des_Cours;
    private javax.swing.JButton BRetour;
    private javax.swing.JButton BStatistique;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
