/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import ptraitement.Client;
import ptraitement.Salle;


/**
 *
 * @author martinant de preneuf
 */
public class FCalendrierCour extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FCalendrierCour.class.getName());
    private Salle salle;
    private Client clientConnecte;
    private String typeActivite;
    private java.time.LocalDate lundiAffiche;
    /**
     * Creates new form FCalendrierCour
     */
    public FCalendrierCour(java.awt.Frame parent, boolean modal,Salle salle,Client client,String type) {
        super(parent, modal);
        initComponents();
        // On force le placement en haut à gauche (0,0)
        this.setLocation(0, 0);

        this.setPreferredSize(new java.awt.Dimension(1100, 700)); // Taille adaptée à votre contenu
        this.pack(); // Applique la taille
        this.setLocationRelativeTo(null); // CENTRE sur l'écran

        // On force le placement en haut à gauche (0,0)
        this.setLocation(0, 0);

        this.salle = salle;
        this.clientConnecte = client;
        this.typeActivite = type;
        // j'ai demandé a chat pour cette ligne le max j'avoue :)
        this.lundiAffiche = java.time.LocalDate.now().with(java.time.temporal.TemporalAdjusters.previousOrSame(java.time.DayOfWeek.MONDAY));
        mettreAJourCalendrier();
    }
    private void mettreAJourCalendrier() {
    // 1. On met à jour les labels des jours avec les dates
    jLundi.setText("Lundi " + lundiAffiche.getDayOfMonth() + "/" + lundiAffiche.getMonthValue());
    jMardi.setText("Mardi " + lundiAffiche.plusDays(1).getDayOfMonth() + "/" + lundiAffiche.plusDays(1).getMonthValue());
    jMercredi.setText("Mercredi " + lundiAffiche.plusDays(2).getDayOfMonth() + "/" + lundiAffiche.plusDays(2).getMonthValue());
    jJeudi.setText("Jeudi " + lundiAffiche.plusDays(3).getDayOfMonth() + "/" + lundiAffiche.plusDays(3).getMonthValue());
    jVendredi.setText("Vendredi " + lundiAffiche.plusDays(4).getDayOfMonth() + "/" + lundiAffiche.plusDays(4).getMonthValue());
    jSamedi.setText("Samedi " + lundiAffiche.plusDays(5).getDayOfMonth() + "/" + lundiAffiche.plusDays(5).getMonthValue());
    jDimanche.setText("Dimanche " + lundiAffiche.plusDays(6).getDayOfMonth() + "/" + lundiAffiche.plusDays(6).getMonthValue());

    
    java.time.format.DateTimeFormatter formateur = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");

    // On applique ce format à la date du lundi
    jAffichageSemaineActuelle.setText("Semaine du " + lundiAffiche.format(formateur));
    
    
    
    remplirListes();
}

private void remplirListes() {
    // On prépare des modèles pour transformer nos objets Cours en texte dans la liste
    javax.swing.DefaultListModel[] models = new javax.swing.DefaultListModel[7];
    for (int i = 0; i < 7; i++) models[i] = new javax.swing.DefaultListModel();

    // On parcourt les cours de la salle
    if (salle != null) {
        for (ptraitement.Cours c : salle.getListeDesCours()) {
            // Est-ce le bon type d'activité ? (Yoga, Muscu...)
            if (c.getNomActivite().equalsIgnoreCase(typeActivite)) {
                // On calcule la différence de jours entre le lundi affiché et la date du cours
                long diff = java.time.temporal.ChronoUnit.DAYS.between(lundiAffiche, c.getDate());
                if (diff >= 0 && diff < 7) {
                    int max = c.getNb_Place_Max();
                    int inscrits = c.getListe_Client_Inscrit().size();
                    int restantes = max - inscrits;
                    models[(int) diff].addElement("heure "+ c.getHeure() + "| Coach " + c.getCoach()+ "|  palces: "+ restantes);
                }
            }
        }
    }

    // On applique les modèles à tes jList1, jList2, etc.
    jList1.setModel(models[0]);
    jList2.setModel(models[1]);
    jList3.setModel(models[2]);
    jList4.setModel(models[3]);
    jList5.setModel(models[4]);
    jList6.setModel(models[5]);
    jList7.setModel(models[6]);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bMonProfil = new javax.swing.JButton();
        panelNavigation = new javax.swing.JPanel();
        bMoisPrecedent = new javax.swing.JButton();
        bSemainePrecedente = new javax.swing.JButton();
        jAffichageSemaineActuelle = new javax.swing.JLabel();
        bSemaineSuivante = new javax.swing.JButton();
        bMoiSuivant = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLundi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jMardi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jMercredi = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jJeudi = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jVendredi = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        jSamedi = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jDimanche = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        PanelBas = new javax.swing.JPanel();
        BMes_Cours = new javax.swing.JButton();
        BInscrire = new javax.swing.JButton();
        bRetour = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        bMonProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimage/logocompteE1.jpg"))); // NOI18N
        bMonProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMonProfilActionPerformed(evt);
            }
        });
        jPanel2.add(bMonProfil, java.awt.BorderLayout.EAST);

        panelNavigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bMoisPrecedent.setText("mois precedent");
        bMoisPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMoisPrecedentActionPerformed(evt);
            }
        });
        panelNavigation.add(bMoisPrecedent);

        bSemainePrecedente.setText("<");
        bSemainePrecedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSemainePrecedenteActionPerformed(evt);
            }
        });
        panelNavigation.add(bSemainePrecedente);

        jAffichageSemaineActuelle.setText("SemaineActuelle");
        panelNavigation.add(jAffichageSemaineActuelle);

        bSemaineSuivante.setText(">");
        bSemaineSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSemaineSuivanteActionPerformed(evt);
            }
        });
        panelNavigation.add(bSemaineSuivante);

        bMoiSuivant.setText("Mois Suivant");
        bMoiSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMoiSuivantActionPerformed(evt);
            }
        });
        panelNavigation.add(bMoiSuivant);

        jPanel2.add(panelNavigation, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLundi.setText("Lundi");
        jPanel1.add(jLundi, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jMardi.setText("Mardi");
        jPanel4.add(jMardi, java.awt.BorderLayout.NORTH);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jMercredi.setText("Mercredi");
        jPanel5.add(jMercredi, java.awt.BorderLayout.NORTH);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jJeudi.setText("Jeudi");
        jPanel6.add(jJeudi, java.awt.BorderLayout.NORTH);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jPanel6.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jVendredi.setText("Vendredi");
        jPanel7.add(jVendredi, java.awt.BorderLayout.NORTH);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jPanel7.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jSamedi.setText("Samedi");
        jPanel8.add(jSamedi, java.awt.BorderLayout.NORTH);

        jScrollPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList6);

        jPanel8.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jDimanche.setText("Dimanche");
        jPanel9.add(jDimanche, java.awt.BorderLayout.NORTH);

        jScrollPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList7);

        jPanel9.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        PanelBas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BMes_Cours.setText("Mes Cours");
        PanelBas.add(BMes_Cours);

        BInscrire.setText("Inscrire");
        BInscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInscrireActionPerformed(evt);
            }
        });
        PanelBas.add(BInscrire);

        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });
        PanelBas.add(bRetour);

        getContentPane().add(PanelBas, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSemainePrecedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSemainePrecedenteActionPerformed
        // TODO add your handling code here:
        lundiAffiche = lundiAffiche.minusWeeks(1);
        mettreAJourCalendrier();
    }//GEN-LAST:event_bSemainePrecedenteActionPerformed

    private void bSemaineSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSemaineSuivanteActionPerformed
        // TODO add your handling code here:
        lundiAffiche = lundiAffiche.plusWeeks(1);
        mettreAJourCalendrier();
    }//GEN-LAST:event_bSemaineSuivanteActionPerformed

    private void bMoisPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoisPrecedentActionPerformed
        // TODO add your handling code here:
    // On recule d'un mois
    this.lundiAffiche = this.lundiAffiche.minusMonths(1);
    // On se recalale sur le lundi pour garder la structure 7 jours
    this.lundiAffiche = this.lundiAffiche.with(java.time.temporal.TemporalAdjusters.previousOrSame(java.time.DayOfWeek.MONDAY));
    
    mettreAJourCalendrier();
    }//GEN-LAST:event_bMoisPrecedentActionPerformed

    private void bMoiSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoiSuivantActionPerformed
        // TODO add your handling code here:
        // On avance d'un mois
    this.lundiAffiche = this.lundiAffiche.plusMonths(1);
    // On se recalale sur le lundi
    this.lundiAffiche = this.lundiAffiche.with(java.time.temporal.TemporalAdjusters.previousOrSame(java.time.DayOfWeek.MONDAY));
    
    mettreAJourCalendrier();
       
    }//GEN-LAST:event_bMoiSuivantActionPerformed

    private void bMonProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMonProfilActionPerformed
        // TODO add your handling code here:
        pfiches.FMonProfil profil = new pfiches.FMonProfil((java.awt.Frame)this.getParent(), true, this.salle, this.clientConnecte);
    
    // 2. On l'affiche
    profil.setVisible(true);
    }//GEN-LAST:event_bMonProfilActionPerformed

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bRetourActionPerformed

    private void BInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInscrireActionPerformed
        // TODO add your handling code here:
        //Vérif état abo client
        if (!clientConnecte.Abo_est_il_actif()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Erreur : Votre abonnement est INACTIF. Veuillez contacter l'administration.", 
                "Abonnement suspendu", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Identifier quelle liste a un cours sélectionné
        javax.swing.JList<String>[] listes = new javax.swing.JList[]{jList1, jList2, jList3, jList4, jList5, jList6, jList7};
        int jourIndex = -1;
        int selectionIndex = -1;

        for (int i = 0; i < listes.length; i++) {
            if (!listes[i].isSelectionEmpty()) {
                jourIndex = i;
                selectionIndex = listes[i].getSelectedIndex();
                break;
            }
        }

        if (jourIndex == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Veuillez sélectionner un cours dans l'une des listes.");
            return;
        }

        //Retrouver Cours correspondant dans la salle
        java.time.LocalDate dateDuCours = lundiAffiche.plusDays(jourIndex);
        ptraitement.Cours coursCible = null;
        int compteur = 0;

        for (ptraitement.Cours c : salle.getListeDesCours()) {
            // On applique les mêmes filtres que pour l'affichage
            if (c.getNomActivite().equalsIgnoreCase(typeActivite) && c.getDate().equals(dateDuCours)) {
                if (compteur == selectionIndex) {
                    coursCible = c;
                    break;
                }
                compteur++;
            }
        }

        //Traitement de l'inscription
        if (coursCible != null) {
            // Vérification des doublons et des places (logique interne à la classe Cours)
            if (coursCible.getListe_Client_Inscrit().contains(clientConnecte)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vous êtes déjà inscrit à ce cours.");
            } 
            else if (coursCible.getListe_Client_Inscrit().size() >= coursCible.getNb_Place_Max()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Désolé, ce cours est complet.");
            } 
            else {
                // Inscription effective
                coursCible.ajouterParticipant(clientConnecte); // Ajoute le client au cours
                clientConnecte.getListe_des_cours_futurs_clients().add(coursCible); // Ajoute le cours au client

                // Sauvegarde automatique (méthode de la classe Salle)
                salle.Sauvegarder();

                javax.swing.JOptionPane.showMessageDialog(this, "Inscription réussie !");

                // 5. Rafraîchir l'affichage
                mettreAJourCalendrier();
            }
        }
    }//GEN-LAST:event_BInscrireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FCalendrierCour dialog = new FCalendrierCour(new javax.swing.JFrame(), true,null,null,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
   
    

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInscrire;
    private javax.swing.JButton BMes_Cours;
    private javax.swing.JPanel PanelBas;
    private javax.swing.JButton bMoiSuivant;
    private javax.swing.JButton bMoisPrecedent;
    private javax.swing.JButton bMonProfil;
    private javax.swing.JButton bRetour;
    private javax.swing.JButton bSemainePrecedente;
    private javax.swing.JButton bSemaineSuivante;
    private javax.swing.JLabel jAffichageSemaineActuelle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jDimanche;
    private javax.swing.JLabel jJeudi;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JLabel jLundi;
    private javax.swing.JLabel jMardi;
    private javax.swing.JLabel jMercredi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jSamedi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel jVendredi;
    private javax.swing.JPanel panelNavigation;
    // End of variables declaration//GEN-END:variables
}
