/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ptraitement.*;
/**
 *
 * @author maxen
 */
public class FGestion_Cours extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FGestion_Cours.class.getName());
    private Salle salle;
    private FAjouter_Cours fichFAjouter_Cours;
    private FModifier_Cours fichFModifier_Cours;
    /**
     * Creates new form FGestion_Cours
     */
    public FGestion_Cours(java.awt.Frame parent, boolean modal, Salle salle) {
        super(parent, modal);
        initComponents();
        this.salle = salle;
        Remplir_Tableau_Cours();
        
        
    }
    
    private void Remplir_Tableau_Cours(){
        String[] colonnes = { "Type", "Activite", "Nombre d'incrits" ,"Places", "Coach", "Date", "Heure"};
        
        //Cours futurs : 
        
        DefaultTableModel Model_Futur = new DefaultTableModel(colonnes, 0);
        List<Cours> Liste_Futur = salle.getListeDesCoursFuturs();
        
        for(Cours c : Liste_Futur) {
            Object[] ligne = {c.getType_de_cours(), c.getNomActivite(), c.getListe_Client_Inscrit().size(), c.getNb_Place_Max(), c.getCoach(), c.getDate(), c.getHeure()};
            Model_Futur.addRow(ligne);
        }
        TCours_Futur.setModel(Model_Futur);
        
        // Cours Passés : 
        
        DefaultTableModel Model_Passe = new DefaultTableModel(colonnes, 0);
        List<Cours> Liste_Passé = salle.getListeDesCoursPasses();
        
        
        for(Cours c : Liste_Passé) {
            Object[] ligne = {c.getType_de_cours(), c.getNomActivite(), c.getListe_Client_Inscrit().size(), c.getNb_Place_Max(), c.getCoach(), c.getDate(), c.getHeure()};
            Model_Passe.addRow(ligne);
        }
        TCours_Passé.setModel(Model_Passe);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BAjouter = new javax.swing.JButton();
        BSupprimer = new javax.swing.JButton();
        BModifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCours_Futur = new javax.swing.JTable();
        BRetour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TCours_Passé = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BAjouter.setText("Ajouter");
        BAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjouterActionPerformed(evt);
            }
        });

        BSupprimer.setText("Supprimer");
        BSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSupprimerActionPerformed(evt);
            }
        });

        BModifier.setText("Modifier");
        BModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifierActionPerformed(evt);
            }
        });

        TCours_Futur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TCours_Futur);

        BRetour.setText("Retour");
        BRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetourActionPerformed(evt);
            }
        });

        jLabel1.setText("Cours Futur");

        jLabel2.setText("Cours Passé");

        TCours_Passé.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TCours_Passé);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(BRetour)
                        .addContainerGap(648, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BAjouter)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BSupprimer)
                                .addGap(18, 18, 18)
                                .addComponent(BModifier))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAjouter)
                    .addComponent(BSupprimer)
                    .addComponent(BModifier)
                    .addComponent(BRetour))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjouterActionPerformed
        // TODO add your handling code here:
        fichFAjouter_Cours = new FAjouter_Cours(null, true, salle);
        fichFAjouter_Cours.setVisible(true);
        Remplir_Tableau_Cours();
    }//GEN-LAST:event_BAjouterActionPerformed

    private void BSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSupprimerActionPerformed
        // TODO add your handling code here:
        int Ligne_Futur = TCours_Futur.getSelectedRow();
        int Ligne_Passé = TCours_Passé.getSelectedRow();
        
        if (Ligne_Futur != -1) {
            
            Cours cours = salle.getListeDesCoursFuturs().get(Ligne_Futur);
            
            if (cours.getListe_Client_Inscrit().size() > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Impossible de supprimer : " + cours.getListe_Client_Inscrit().size() + " client(s) déjà inscrit(s) !", "Action refusée", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                int choix = javax.swing.JOptionPane.showConfirmDialog(this, "Etes vous sur de vouloir supprimer le cours de " + cours.getType_de_cours() + " du " + cours.getDate() + " ?","Confirmation de suppression", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
            
                if(choix == javax.swing.JOptionPane.YES_OPTION){
                    salle.getListeDesCoursFuturs().remove(Ligne_Futur);
                    salle.Sauvegarder();
                    Remplir_Tableau_Cours();
                    javax.swing.JOptionPane.showMessageDialog(this, "Cours supprime avec succes.");

            }}
        } else if (Ligne_Passé != -1) {
            Cours cours = salle.getListeDesCoursPasses().get(Ligne_Passé);
            int choix = javax.swing.JOptionPane.showConfirmDialog(this, "Etes vous sur de vouloir supprimer le cours de " + cours.getType_de_cours() + " du " + cours.getDate() + " ?","Confirmation de suppression", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

            if(choix == javax.swing.JOptionPane.YES_OPTION){
                salle.getListeDesCoursPasses().remove(Ligne_Passé);
                salle.Sauvegarder();
                Remplir_Tableau_Cours();
                javax.swing.JOptionPane.showMessageDialog(this, "Cours supprime avec succes");      
            }else {
                javax.swing.JOptionPane.showMessageDialog(this, "veuillez selectionner un cours dans le tableau ");
            }
        }
        
    }//GEN-LAST:event_BSupprimerActionPerformed

    private void BModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifierActionPerformed
        // TODO add your handling code here:
        //recup la ligne selectionner
        int Ligne_Futur = TCours_Futur.getSelectedRow();
        if(Ligne_Futur != -1){
            Cours Cours_Choisie = salle .getListeDesCoursFuturs().get(Ligne_Futur);
            FModifier_Cours fichFModifier_Cours = new FModifier_Cours(null, true, salle, Cours_Choisie);
            fichFModifier_Cours.setVisible(true);
            Remplir_Tableau_Cours();
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un cours dans le tableau 'Cours Futur'.");
        }
    }//GEN-LAST:event_BModifierActionPerformed

    private void BRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.getParent().setVisible(true);
    }//GEN-LAST:event_BRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FGestion_Cours dialog = new FGestion_Cours(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAjouter;
    private javax.swing.JButton BModifier;
    private javax.swing.JButton BRetour;
    private javax.swing.JButton BSupprimer;
    private javax.swing.JTable TCours_Futur;
    private javax.swing.JTable TCours_Passé;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
