/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;
import javax.swing.JOptionPane;
import ptraitement.*;

/**
 *
 * @author maxen
 */
public class FInscription extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FInscription.class.getName());
    private Salle salle;
    /**
     * Creates new form FInscription
     */
    public FInscription(java.awt.Frame parent, boolean modal, Salle salle) {
        super(parent, modal);
        initComponents();
        this.setPreferredSize(new java.awt.Dimension(900, 600)); // Taille adaptée à votre contenu
        this.pack(); // Applique la taille
        this.setLocationRelativeTo(null); // CENTRE sur l'écran
        this.salle = salle;
        javax.swing.ButtonGroup groupeAbo = new javax.swing.ButtonGroup();
        groupeAbo.add(BMensuel);
        groupeAbo.add(BTrimestiel);
        groupeAbo.add(BAnnuel);
        BMensuel.setSelected(true);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BRetour = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BInscription = new javax.swing.JButton();
        TXTMDP = new javax.swing.JTextField();
        TXTMail = new javax.swing.JTextField();
        TXTPrénom = new javax.swing.JTextField();
        TXTNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTTéléphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BMensuel = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        BTrimestiel = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        BAnnuel = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BRetour.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BRetour.setText("Retour");
        BRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetourActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mail : ");

        BInscription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BInscription.setText("Inscription");
        BInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInscriptionActionPerformed(evt);
            }
        });

        TXTMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTMailActionPerformed(evt);
            }
        });

        TXTNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNomActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Abonnement :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mot de passe : ");

        TXTTéléphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTéléphoneActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Téléphone :");

        BMensuel.setText("mensuel");
        BMensuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMensuelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Inscription : ");

        BTrimestiel.setText("trimestriel");
        BTrimestiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTrimestielActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nom : ");

        BAnnuel.setText("annuel");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Prénom :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Avec Thibaut et Maxence, la forme c'est une évidence !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BInscription)
                        .addGap(82, 82, 82)
                        .addComponent(BRetour))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXTTéléphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(TXTMDP)
                            .addComponent(TXTMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTPrénom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTNom, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BMensuel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTrimestiel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BAnnuel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BMensuel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTrimestiel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BAnnuel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TXTMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTTéléphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BInscription)
                    .addComponent(BRetour))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInscriptionActionPerformed
        // TODO add your handling code here:
        String email = TXTMail.getText();
        String mdp = TXTMDP.getText();
        String Nom = TXTNom.getText();
        String Prenom = TXTPrénom.getText();
        String Tel = TXTTéléphone.getText();
        String abonnement = "";
        if (BMensuel.isSelected()) abonnement = "Mensuel";
        else if (BTrimestiel.isSelected()) abonnement = "Trimestriel";
        else if (BAnnuel.isSelected()) abonnement = "Annuel";

        if (Nom.isEmpty() || email.isEmpty() || abonnement.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Veuillez remplir les informations et choisir un abonnement.");
            return;
        }
        if (!email.contains("@") || !email.contains(".")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Adresse email invalide. Elle doit contenir '@' et '.'");
        return;
        }
        if (!Tel.matches("\\d{10}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Numéro de téléphone invalide. Il doit contenir exactement 10 chiffres.");
        return;
        }
        for (Client c : salle.getListeDesClients()) {
         if (c.getEmail().equals(email)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cet email est déjà utilisé par un autre client.");
        return;
        }
        }
        String numClient = "C" + (salle.getListeDesClients().size() + 1); // Numéro de client 
        
        Client NouveauClient = new Client(numClient, Nom, Prenom, email, mdp, Tel, abonnement);
        salle.getListeDesClients().add(NouveauClient);
        
        salle.Sauvegarder();
        
        JOptionPane.showMessageDialog(this, "Inscription réussie! Voici votre numéro de client : " + numClient);
        this.setVisible(false);
        this.getParent().setVisible(true);
        

    }//GEN-LAST:event_BInscriptionActionPerformed

    private void TXTTéléphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTéléphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTéléphoneActionPerformed

    private void TXTNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNomActionPerformed


    private void BMensuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMensuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BMensuelActionPerformed

    private void BRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        getParent().setVisible(true);
    }//GEN-LAST:event_BRetourActionPerformed

    private void BTrimestielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTrimestielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTrimestielActionPerformed

    private void TXTMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTMailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXTMailActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FInscription dialog = new FInscription(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BAnnuel;
    private javax.swing.JButton BInscription;
    private javax.swing.JRadioButton BMensuel;
    private javax.swing.JButton BRetour;
    private javax.swing.JRadioButton BTrimestiel;
    private javax.swing.JTextField TXTMDP;
    private javax.swing.JTextField TXTMail;
    private javax.swing.JTextField TXTNom;
    private javax.swing.JTextField TXTPrénom;
    private javax.swing.JTextField TXTTéléphone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
