/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import ptraitement.*;
/**
 *
 * @author maxen
 */
public class FMes_Cours extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FMes_Cours.class.getName());
    private Client Client_Connecte;
    private Salle salle;
    /**
     * Creates new form FMes_Cours
     */
    public FMes_Cours(java.awt.Frame parent, boolean modal, Client client, Salle salle) {
        super(parent, modal);
        initComponents();
        this.salle = salle;
        this.Client_Connecte = client;
        
        this.setTitle("Mes Inscription : " + client.getPrenom() + " " + client.getNom());
        
        Remplir_Tableau(TCours_Futur, Client_Connecte.getListe_des_cours_futurs_clients());
        Remplir_Tableau(TCours_Passé, Client_Connecte.getListe_des_cours_passes_clients());
        
        this.setLocationRelativeTo(parent);
    }

    
    private void Remplir_Tableau(javax.swing.JTable tableau, List<Cours> liste){
        
       // 1. On définit les noms des colonnes
    String[] colonnes = {"Activité", "Coach", "Date", "Heure", "Type"};
    
    // 2. On crée le modèle avec les titres (0 ligne au départ)
    DefaultTableModel model = new DefaultTableModel(colonnes, 0);
    
    // 3. On remplit les données
    if (liste != null) {
        for (Cours c : liste) {
            Object[] ligne = {
                c.getNomActivite(), 
                c.getCoach(), 
                c.getDate().toString(), 
                c.getHeure(), 
                c.getType_de_cours()
            };
            model.addRow(ligne);
        }
    }
    
    // 4. On applique le nouveau modèle au tableau pour afficher les titres
    tableau.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TCours_Futur = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TCours_Passé = new javax.swing.JTable();
        BSe_Deinscrire = new javax.swing.JButton();
        BRetour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TCours_Futur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TCours_Futur);

        TCours_Passé.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TCours_Passé);

        BSe_Deinscrire.setText("Se déinscrire");
        BSe_Deinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSe_DeinscrireActionPerformed(evt);
            }
        });

        BRetour.setText("Retour");
        BRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetourActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cours Futurs");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cours passés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(BSe_Deinscrire)
                .addGap(93, 93, 93)
                .addComponent(BRetour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(340, 340, 340))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSe_Deinscrire)
                    .addComponent(BRetour))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSe_DeinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSe_DeinscrireActionPerformed
        // TODO add your handling code here:
        int ligne = TCours_Futur.getSelectedRow();
        
        if (ligne == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Veuillez sélectionner un cours à annuler.");
            return;
        }
        
        ptraitement.Cours coursSelectionne = Client_Connecte.getListe_des_cours_futurs_clients().get(ligne);
        
        int Confirmation = javax.swing.JOptionPane.showConfirmDialog(this,
                "Voulez-vous vraiment vous désinscrire du cours de " + coursSelectionne.getNomActivite() + " ?",
                "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (Confirmation == javax.swing.JOptionPane.YES_OPTION){
            coursSelectionne.getListe_Client_Inscrit().remove(Client_Connecte);
        
        Client_Connecte.getListe_des_cours_futurs_clients().remove(coursSelectionne);

        salle.Sauvegarder();
        
        Remplir_Tableau(TCours_Futur, Client_Connecte.getListe_des_cours_futurs_clients());
        
        javax.swing.JOptionPane.showMessageDialog(this, "Désinscription effectuée.");
        }
    }//GEN-LAST:event_BSe_DeinscrireActionPerformed

    private void BRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetourActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FMes_Cours dialog = new FMes_Cours(new javax.swing.JFrame(), true, null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRetour;
    private javax.swing.JButton BSe_Deinscrire;
    private javax.swing.JTable TCours_Futur;
    private javax.swing.JTable TCours_Passé;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
